const cenarios = [
    [
        "","","","","","","","","","","","","","","","","","","","","","","","",
        "","","","","","","","","","","","","","",
        "                                                         m",
        "                                         bbbbb         bbbbb",
        "",
        "",
        "                                   bbbb         bbbbb",
        "",
        "",
        "                    bbbbb  v            m",
        "                             bbbb      bbbb",
        "              m               bbbllllllbbbb",
        "            bbbbb             bbbllllllbbbb",
        "   @                          bbbllllllbbbb",
        "  bbbbbbb                     bbbbbbbbbbbbb"
    ],
    [
        "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
        "                    bbbbbbbbbb          bbbbbbbbbbbbbbbbbbbb",
        "                    b                                      b",
        "                    b                                      b",
        "                    b                                      b",
        "                    b                                      b",
        "                  bbb                                      bbbbbbbbbbb",
        "                  b                                                  b",
        "                  b                                                  b",
        "                  b                                                  b",
        "            @     b                                                  b",
        "           bbbbbbbb          bbbbbbbbbb                              b",
        "           b                                                         b",
        "           b                                                         b",
        "           b                                                         b",
        "           b                                                         b",
        "           b                                                         b",
        "           b                                bbbbbbbbbbb              b",
        "           b                                                         b",
        "           b                                                         b",
        "           b                                                         b",
        "  bbbbbbbbbb                                             V           b",
        "  b                                                           m      b",
        "  b                      bbbbbbb                           bbbbbb    b",
        "  b                                                                  b",
        "  b                         H                                        b",
        "  b               m                   m                              b",
        "  b           bbbbbbbbbb         bbbbbbbbbbbbbbbbbbbbb               b",
        "  b                                                                  b",
        "  b                                                                  b",
        "  b                                                                  b",
        "  b                                                                  b",
        "  b                         h                                        b",
        "  b                                                                  b",
        "  b                                                                  b",
        "  b                                                                  b",
        "  b                                                                  b",
        "  b                   b          b                                   b",
        "  blllllllllllllllllllb     m    blllllllllllllllllllllllllllllllllllb",
        "  blllllllllllllllllllb    bbb   blllllllllllllllllllllllllllllllllllb",
        "  blllllllllllllllllllb          blllllllllllllllllllllllllllllllllllb",
        "  blllllllllllllllllllb          blllllllllllllllllllllllllllllllllllb",
        "  blllllllllllllllllllb          blllllllllllllllllllllllllllllllllllb",
        "  blllllllllllllllllllb          blllllllllllllllllllllllllllllllllllb",
        "  blllllllllllllllllllb          blllllllllllllllllllllllllllllllllllb",
        "  blllllllllllllllllllb          blllllllllllllllllllllllllllllllllllb",
        "  blllllllllllllllllllb          blllllllllllllllllllllllllllllllllllb",
        "  blllllllllllllllllllb          blllllllllllllllllllllllllllllllllllb",
        "  bbbbbbbbbbbbbbbbbbbbb          bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"
    ]    
]

